server:
  port: 8080

cassandra:
  contactpoints: localhost
  port: 9042
  keyspace: pet_mgt

app:
  toggles:
    - name: activate-cassandra-rw
      active: false
    - name: activate-in-memory-rw
      active: true
