name: Build and Publish Docker
on:
  pull_request:
    paths:
    - 'backend-api/**'
  push:
    paths:
    - 'backend-api/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker Image
      - run: docker build . -f backend-api/Dockerfile -t pms-api:beta-$(date +%s)