name: Build and Publish Docker
on:
  push:
    paths:
    pull_request:
    - 'backend-api/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -f backend-api/Dockerfile -t pms-api:beta-${{ GITHUB_SHA }} .